#L2X9AntiBot by 254n_m
#Go to google.com/recaptcha/ to generate a new site key 

#WebServer port
port: 25594
#Site keys
Site-Key: "6LfYDeMUAAAAAG0I-RkGVT49l1V0IgazaT2aKBhI"
Private-Key: "6LfYDeMUAAAAAOzZgErh--4AjdA8kzEHy22h5rys"

#Messages
#Kick on chat / command / timeout
Kick-Message: "&3[L2X9AntiBot]&r&4 Please verify you are not a bot at&r&a antibot.l2x9.org\n\n&3[L2X9AntiBot]&r&4 Verifica que no eres un bot en&r&a antibot.l2x9.org"
#Message to send the player when they are not verified
Not-Verified-Message: 
  - "&3[L2X9AntiBot]&r&4 Please verify you are not a bot at&r&a antibot.l2x9.org"
  - "&3[L2X9AntiBot]&r&4 Verifica que no eres un bot en&r&a antibot.l2x9.org"
  - "&k-----------------------------------------------------"
  - "&3[L2X9AntiBot]&r&4 Please verify you are not a bot at&r&a antibot.l2x9.org"
  - "&3[L2X9AntiBot]&r&4 Verifica que no eres un bot en&r&a antibot.l2x9.org"
  - "&k-----------------------------------------------------"
  - "&3[L2X9AntiBot]&r&4 Please verify you are not a bot at&r&a antibot.l2x9.org"
  - "&3[L2X9AntiBot]&r&4 Verifica que no eres un bot en&r&a antibot.l2x9.org"
  - "&k-----------------------------------------------------"
#Options
#Set true to enable. This option will spam Not-Verified-Message in the chat every one second
Spam-the-player-to-whitelist: false
#How long the player has before they get kicked for inactivity in seconds
Verify-Timeout: 60
#Action bar message use %time as a place holder for the time
ActionBar-Message: '&6&lPlease verify at AntiBot.l2x9.org to play&r&b&l L2X9&r&c&l %time%'